package MedicalStore;


/**
* MedicalStore/medintf.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* martes 28 de febrero de 2023 23H43' CET
*/

public interface medintf extends medintfOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface medintf
