package MedicalStore;


/**
* MedicalStore/medintfHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* martes 28 de febrero de 2023 23H43' CET
*/

abstract public class medintfHelper
{
  private static String  _id = "IDL:MedicalStore/medintf:1.0";

  public static void insert (org.omg.CORBA.Any a, MedicalStore.medintf that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MedicalStore.medintf extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MedicalStore.medintfHelper.id (), "medintf");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MedicalStore.medintf read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_medintfStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MedicalStore.medintf value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MedicalStore.medintf narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MedicalStore.medintf)
      return (MedicalStore.medintf)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MedicalStore._medintfStub stub = new MedicalStore._medintfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MedicalStore.medintf unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MedicalStore.medintf)
      return (MedicalStore.medintf)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MedicalStore._medintfStub stub = new MedicalStore._medintfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
