package MedicalStore;


/**
* MedicalStore/medintfPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* martes 28 de febrero de 2023 23H43' CET
*/

public abstract class medintfPOA extends org.omg.PortableServer.Servant
 implements MedicalStore.medintfOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("check_medicine", new java.lang.Integer (0));
    _methods.put ("process_medicine", new java.lang.Integer (1));
    _methods.put ("form_medicine", new java.lang.Integer (2));
    _methods.put ("ver_cesta", new java.lang.Integer (3));
    _methods.put ("total_price", new java.lang.Integer (4));
    _methods.put ("pay_bill", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MedicalStore/medintf/check_medicine
       {
         String med_id = in.read_string ();
         String $result = null;
         $result = this.check_medicine (med_id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // MedicalStore/medintf/process_medicine
       {
         String med_id = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.process_medicine (med_id, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // MedicalStore/medintf/form_medicine
       {
         String med_id = in.read_string ();
         String $result = null;
         $result = this.form_medicine (med_id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // MedicalStore/medintf/ver_cesta
       {
         String $result = null;
         $result = this.ver_cesta ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // MedicalStore/medintf/total_price
       {
         int $result = (int)0;
         $result = this.total_price ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // MedicalStore/medintf/pay_bill
       {
         String $result = null;
         $result = this.pay_bill ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MedicalStore/medintf:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public medintf _this() 
  {
    return medintfHelper.narrow(
    super._this_object());
  }

  public medintf _this(org.omg.CORBA.ORB orb) 
  {
    return medintfHelper.narrow(
    super._this_object(orb));
  }


} // class medintfPOA
