package MedicalStore;


/**
* MedicalStore/MedicineInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Saturday, 14 April, 2018 10:58:32 AM IST
*/

public final class MedicineInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public int count = (int)0;
  public int price = (int)0;

  public MedicineInfo ()
  {
  } // ctor

  public MedicineInfo (String _name, int _count, int _price)
  {
    name = _name;
    count = _count;
    price = _price;
  } // ctor

} // class MedicineInfo